### ISSUE TITLE
Requesting a new PyLadies Chapter website: PyLadies Dublin

### ISSUE THREAD

**Issue by whykay** [pyladies/chapter-websites#11]
_This template should be used for those requiring a new PyLadies website._

## What is the name of the PyLadies chapter requesting the website?
PyLadies Dublin

## What is the custom domain desired for the PyLadies chapter website?
Already have one: dublin.pyladies.com

## What are the GitHub handles of the PyLadies chapter organizers?

Name | GitHub Handle | Slack Handle | Team Role |
| -- | --  | --  | -- |
| Vicky Twomey-Lee | @whykay | @whykay - PyLadies Dublin | Organiser | 

## Do you want your website to use one of the following templates or do you prefer it to be blank?

- [ ] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
- [X] I'll use my own template

## Where will you host the website?

- [X] GitHub Pages
- [ ] Heroku
- [ ] Netlify
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
- [X] Completed the 5 questions above
- [X] Did you notify the PyLadies Slack channel #project-tech-infra?
- [X] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2).
      Insert pull request: #12 
- [ ] If applicable, have you removed your old PyLadies website from main PyLadies repo? 
      Insert pull request: [Add pull request link here]

**For the @pyladies/tech-and-infra-admins to complete:**
- [x] Insert link to repo:https://github.com/pyladies/pyladies-dublin-website
- [x] Is the custom domain created?
- [x] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team: @pyladies/dublin 
- [x] Is the GitHub team added to the repo with maintain permissions? 
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/4573607/86634252-3cd85980-bf97-11ea-8f6d-70c6d2099840.png">

/cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
@whykay hi hi hi! OK so the intent here is for PyLadies to start streamlining our repos, moving the PyLadies chapter websites into our `pyladies` GitHub organization. That's why I made a for of your existing repo and made: https://github.com/pyladies/pyladies-dublin-website. I'll add this submodule and point the sub domain to this repo. You've been given all the powers for maintaining.

**Comment by lorenanicole** [comment]
Question: Did you want the netlify preview setup on the https://github.com/pyladies/pyladies-dublin-website repo? If so, you'll need to add the netlify badge to your page e.g.  like [Chicago](chicago.pyladies.com) below. 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/4573607/86636060-79a55000-bf99-11ea-93e2-2f61d1495e2d.png">

**Comment by lorenanicole** [comment]
@whykay can you follow up on the above? Or else we'll be moving to close this. Also are there any other coorganizers we should be inviting ?

**Comment by whykay** [comment]
Sorry, didn't get a chance to answer. Can you explain what you mean by "Did you want the netlify preview setup on the https://github.com/pyladies/pyladies-dublin-website repo?" - I don't know what I should be doing from my end as it's only on gitpages at the moment/

Thanks.

**Comment by lorenanicole** [comment]
All I need to know @whykay is if you'd like to use Netlify to build previews for each PR that is opened against your `gh-pages` branch! Here's an example of how that works in the PyLadies Chicago website repo: https://github.com/pyladies/pyladies-chicago-website/pull/1. Each time a PR is opened against your default branch (e.g. `gh-pages` if you host your website on GitHub pages) a preview is built to confirm the build looks as your expect. You can see if in the 'checks' that run via the `deploy-preview` check:

![image](https://user-images.githubusercontent.com/4573607/88832116-f2ad5700-d195-11ea-9925-cd954ee2979e.png)

That gives you a deploy url like https://deploy-preview-2--thirsty-liskov-172d04.netlify.app/. We also use it on github.com/pyladies/pyladies. Example of a deploy preview from a recent PyLadies PR closed and merged: https://deploy-preview-531--pyladies.netlify.app/.
