### ISSUE TITLE
Requesting a new PyLadies Chapter website: PyLadies São Carlos

### ISSUE THREAD

**Issue by julianaklulo** [pyladies/chapter-websites#13]
_This template should be used for those requiring a new PyLadies website._

## What is the name of the PyLadies chapter requesting the website?
São Carlos

## What is the custom domain desired for the PyLadies chapter website?
saocarlos.pyladies.com

## What are the GitHub handles of the PyLadies chapter organizers?

Name | GitHub Handle | Slack Handle | Team Role 
| --| --| --| --| 
Juliana Karoline | julianaklulo | julianaklulo | Co-Organizer
Ana Dulce | anadulce | anadulce | Co-Organizer
Nathalia Gomazako | n-th | n-th | Co-Organizer
Laura Gouveia | volkana | Laura G | Co-Organizer

## Do you want your website to use one of the following templates or do you prefer it to be blank?

- [ ] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
- [x] I'll use my own template

## Where will you host the website?

- [x] GitHub Pages
- [ ] Heroku
- [ ] Netlify
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
- [x] Completed the 5 questions above
- [x] Did you notify the PyLadies Slack channel #project-tech-infra?
- [x] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2).
      Insert pull request: https://github.com/pyladies/chapter-websites/pull/14
- [x] If applicable, have you removed your old PyLadies website from main PyLadies repo? 
      Insert pull request: https://github.com/pyladies/pyladies/pull/529

**For the @pyladies/tech-and-infra-admins to complete:**
- [x] Insert link to repo: https://github.com/pyladies/pyladies-sao-carlos-website
- [x] Is the custom domain created?
- [x] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team: @pyladies/sao-carlos 
- [x] Is the GitHub team added to the repo with maintain permissions? Yes see screenshot below

![image](https://user-images.githubusercontent.com/4573607/88682387-3af64780-d0b8-11ea-9194-49eb80a065d7.png)

/cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
You've all been added to the @pyladies/sao-carlos team, please accept those invites in order to use the repo.

![image](https://user-images.githubusercontent.com/4573607/88680518-3466d080-d0b6-11ea-83fc-8daf202476a2.png)

**Comment by lorenanicole** [comment]
@julianaklulo  your repo has been made if you want to start adding all your content to it! Did you want to use netlify for generating previews of your website? If so please tell me. When you are ready and have your local repo setup with all your design, remember you'll need to add:
-  a `CNAME` file with your subdomain
- add a pull request to remove your old website from github.com/pyladies/pyladies
- add a pull request to add your website as a submodule to this repo, the instructions are in the readme for how to do that

When the above is done I'll move the subdomain to point to the proper location.

**Comment by julianaklulo** [comment]
@lorenanicole I've added the pull requests to remove the old website and to add the new one as a submodule.

**Comment by BethanyG** [comment]
Approved and merged https://github.com/pyladies/chapter-websites/pull/14 (**_add new repo as submodule_**)
Approved and merged https://github.com/pyladies/pyladies/pull/529 (**_remove old repo from monolith main website_**)

**Comment by lorenanicole** [comment]
Commenting, as we have yet to investigate the old hosting DNS rules to see if this is what is causing the issue with the old domain.
