### ISSUE TITLE
Requesting a new PyLadies Chapter website: PyLadies Seattle

### ISSUE THREAD

**Issue by catherinenelson1** [pyladies/chapter-websites#15]
_This template should be used for those requiring a new PyLadies website._

## What is the name of the PyLadies chapter requesting the website? 
Seattle

## What is the custom domain desired for the PyLadies chapter website? 
seattle.pyladies.com (or similar!)

## What are the GitHub handles of the PyLadies chapter organizers?

Name | GitHub Handle | Slack Handle | Team Role 
| --| --| --| --| 
Catherine Nelson | drcat101 | Catherine Nelson | Co-organizer
Wendy Grus | wgrus |  wendy_seattle | Organizer
Christy Heaton | christyheaton | Christy Heaton | Co-organizer
Erika Pelaez | MidoriR | Erika Pelaez | Co-organizer

## Do you want your website to use one of the following templates or do you prefer it to be blank?

-  [X] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
-  [ ] I'll use my own template

## Where will you host the website?

- [X] GitHub Pages
- [ ] Heroku
- [ ] Netlify
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
-  [x] Completed the 5 questions above
-  [x] Did you notify the PyLadies Slack channel #project-tech-infra?
-  [ ] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2).
      Insert pull request: [Add pull request link here]
-  [x] If applicable, have you removed your old PyLadies website from main PyLadies repo? 
      Insert pull request: https://github.com/pyladies/pyladies/pull/531

**For the @pyladies/tech-and-infra-admins to complete:**
-  [x] Insert link to repo: https://github.com/pyladies/pyladies-seattle-website
-  [x] Is the custom domain created?
-  [x] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team:  https://github.com/orgs/pyladies/teams/seattle
-  [x] Is the GitHub team added to the repo with maintain permissions?

/cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
@drcat101 the PR has been approved and merged into github.com/pyladies/pyladies (see: https://github.com/pyladies/pyladies/pull/531/files). Also the subdomain has been updated to point to your `gh-pages` branch on https://github.com/pyladies/pyladies-seattle-website. Basically all you need to do is add your project content to the repo!

**Comment by lorenanicole** [comment]
Ah, actually looks like @BethanyG made your repo with the blank gh template if you'd @drcat101 like to use the netlify template from this template repo https://github.com/pyladies/netlify-website-template let me know and I can remake your repo off that.

**Comment by BethanyG** [comment]
Remade the repo with the Netlify template.  Netlify preview available at `seattle.pyladies.com`.

**Comment by lorenanicole** [comment]
@drcat101 to close this out, can you take care of the last item by adding your repo as submodule to this repo? 

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/4573607/89237882-fd168900-d5b9-11ea-8ce3-13e280993121.png">

**Comment by catherinenelson1** [comment]
@lorenanicole from the way this documentation https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule is written, I thought that was something I only had to do if I was continuing to use our old website. I'll do that right away, and I'll also submit a PR to update the docs so it's clearer!

**Comment by catherinenelson1** [comment]
so, I cloned the chapter-websites repo, and entered the following commands as stated in the docs:
`git submodule add -b gh-pages https://github.com/pyladies/pyladies-seattle-website seattle`
`git submodule init`
but I don't have permission to push to this repo. What am I doing wrong?
