### ISSUE TITLE
Requesting a new PyLadies Chapter website: Hamburg

### ISSUE THREAD

**Issue by terezaif** [pyladies/chapter-websites#16]
_This template should be used for those requiring a new PyLadies website._

## What is the name of the PyLadies chapter requesting the website?

Hamburg 
## What is the custom domain desired for the PyLadies chapter website?

hamburg.pyladies.com
## What are the GitHub handles of the PyLadies chapter organizers?

terezaif, neinkeinkaffee, chalendony, 

Name | GitHub Handle | Slack Handle | Team Role 
| -- | -- | -- | -- |
| Tereza Iofciu | terezaif| Tereza| co-organiser | 
| Gesa Stupperich | neinkeinkaffee | Gesa| co-organiser | 
| Avaré Stewart | chalendony | Avaré Stewart| co-organiser | 
| Annemarie Paul | AnMaPa | Annemarie Paul | co-organiser | 

## Do you want your website to use one of the following templates or do you prefer it to be blank?

- [x] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
- [ ] [PyLadies Website served via GitHub Pages with my own design](https://github.com/pyladies/chapter-websites/issues/13#issuecomment-665090083)
- [ ] Fork our existing PyLadies repo
         Insert repo name: [Add repo name here]
- [ ] I'll use my own template

## Where will you host the website?

- [x] GitHub Pages
- [ ] Heroku
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
- [x] Completed the 5 questions above
- [x] Did you notify the PyLadies Slack channel #project-tech-infra?
- [x] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2).
      Insert pull request: [https://github.com/pyladies/chapter-websites/pull/19]
- [x] If applicable, have you removed your old PyLadies website from main PyLadies repo? 
      Insert pull request: [https://github.com/pyladies/pyladies/pull/532]

**For the @pyladies/tech-and-infra-admins to complete:**
- [x] Insert link to repo: https://github.com/pyladies/pyladies-hamburg-website
- [x] Is the custom domain created?
- [x] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team: @pyladies/hamburg
- [x] Is the GitHub team added to the repo with maintain permissions?

/cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
@tereza question:
- Is this code for your current website https://github.com/pyladies/pyladies/tree/main/hamburg? If so, we'll open you an empty repo and you can add that info there. 
- If not, do you want the netlify template that you specified above (please see chicago.pyladies.com as an example of the final build)?
![image](https://user-images.githubusercontent.com/4573607/88831106-7d8d5200-d194-11ea-9d12-4902a2dfd053.png)
- If none of those, then no worries we'll just make you an empty repo and you all can do as you see fit :D

**Comment by lorenanicole** [comment]
@terezaif confirmed in Slack their chapter wants to use the [Netlify template](https://pyladies.slack.com/archives/CU158UC15/p1596047957190800?thread_ts=1596041685.188800&cid=CU158UC15)

**Comment by BethanyG** [comment]
Created CNAME and CODEOWNERS.  Netlify preview can be seen via https://pyladies-hamburg.netlify.app/ which mirrors what is currently deploed and hosted via GitHub pages at `hamburg.pyladies.com`

**Comment by lorenanicole** [comment]
@terezaif to close this out can you please open a PR to add your repo as a submodule to this repo as well as link the PR that removed your old project code from the pyladies monolith? Thanks!

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/4573607/89237837-db1d0680-d5b9-11ea-9267-f4ff1be1b230.png">

**Comment by terezaif** [comment]
Can you pls add AnMaPa (Annemarie's handle) as codeowner?

**Comment by BethanyG** [comment]
@terezaif  -- Apologies for the delay.  I sent an invite to the Hamburg Organizers team to @AnMaPa -- that should give codeowner access.  Please let me know if it doesn't.

**Comment by BethanyG** [comment]
@terezaif  -- Noticed today that you haven't added your repo as a submodule to this one yet, so just a friendly reminder.  😄

**Comment by terezaif** [comment]
@BethanyG I am really confused :smile: regarding the website.. i made a pr to pyladies/pyladies-hamburg-website .. this I have to add as a submodule? ( I'll .. google that :D )

**Comment by terezaif** [comment]
@BethanyG done now!!

**Comment by BethanyG** [comment]
@lorenanicole @terezaif -- Just merged the Submodule PR (https://github.com/pyladies/chapter-websites/pull/19).  

Unless there is anything else I've forgotten, I think we're good to close this!  I will leave it open for another day or so, and then close if nothing else comes up.

**Comment by BethanyG** [comment]
@lorenanicole  -- Forgot to merge https://github.com/pyladies/pyladies-hamburg-website/pull/1 until just now.  When you get a chance, can you walk me (or point me to instructions) through pulling in an update to the Hamburg submodule?  Should I clone down this repo and do it locally and re-push, or is there an easier GitHub only way of doing it??

**Comment by lorenanicole** [comment]
Yah the update needs to be done locally. Basically just pull it down and run `git submodule update`! https://chrisjean.com/git-submodules-adding-using-removing-and-updating/ is a great write up.
