### ISSUE TITLE
Requesting a new PyLadies Chapter website: Madrid

### ISSUE THREAD

**Issue by aliciapj** [pyladies/chapter-websites#18]
_This template should be used for those requiring a new PyLadies website._

## What is the name of the PyLadies chapter requesting the website?
Madrid

## What is the custom domain desired for the PyLadies chapter website?
madrid.pyladies.com

## What are the GitHub handles of the PyLadies chapter organizers?
aliciapj, mariamedp, vickycmcv

| Name | GitHub Handle | Slack Handle | Team Role |
| ---- | ---- | ---- | ---- |
| Alicia Pérez | aliciapj | aliciapj | co-organizer |
| María Medina | mariamedp | mariamedp | co-organizer |
| Vicky Cortés | vickycmcv | Vicky Cortes | co-organizer | 

## Do you want your website to use one of the following templates or do you prefer it to be blank?

- [ ] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
- [ ] [PyLadies Website served via GitHub Pages with my own design](https://github.com/pyladies/chapter-websites/issues/13#issuecomment-665090083)
- [x] Fork our existing PyLadies repository to use existing design
       Insert repo name: https://github.com/pyladies/pyladies  -- not really a fork
- [ ] I'll use my own template

## Where will you host the website?

- [ ] GitHub Pages
- [ ] Heroku
- [x] Netlify
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
- [x] Completed the 5 questions above
- [x] Did you notify the PyLadies Slack channel #project-tech-infra?
- [x] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2).
      Insert pull request: https://github.com/pyladies/chapter-websites/pull/17
- [ ] If applicable, have you removed your old PyLadies website from main PyLadies repo? 
      Insert pull request: [Add pull request link here]

**For the @pyladies/tech-and-infra-admins to complete:**
- [X] Insert link to repo: https://github.com/pyladies/pyladies-madrid-website
- [X] Is the custom domain created? madrid.pyladies.com
- [X] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team: @pyladies/madrid 
- [X] Is the GitHub team added to the repo with maintain permissions?

/cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
Oh drats, we should have made you a repo. Thanks for adding your website in, however  are trying to have all repos owned by PyLadies.  I'll fork your website and get it all setup. Then I'll update with the proper repo as a submodule.

**Comment by lorenanicole** [comment]
@aliciapj https://github.com/pyladies/pyladies-madrid-website is the forked copy of you website.  I setup a GitHub action to on any push event to main branch to rebuild and push the code to the `gh-pages` branch. Your subdomain is  madrid.pyladies.com!

**Comment by lorenanicole** [comment]
If you want to use your repo still, that's fine! If you can push your changes then into the fork that'll work for us :-).

**Comment by lorenanicole** [comment]
@aliciapj cc/ @pyladies/madrid can you all confirm you understand the changes I noted above?

**Comment by aliciapj** [comment]
Hi @lorenanicole!

Understood :+1: 

And being able to merge the PRs in this repo, it's totally fine for us to use this repo as "official repo" for the Madrid website, so **thank you a lot!** 

Since we opened this PR we have been developing a new version using the marble theme that you are using in the elections webpage (preview here: https://pyladiesmadrid.netlify.app/), so I'll update this repo with the new files this weekend and hopefully everything will work after that :smiley: 

Thank you again and happy weekend!

**Comment by lorenanicole** [comment]
Thanks @aliciapj ! I'll close out this issue then.
