### ISSUE TITLE
Requesting a new PyLadies Chapter website: PyLadies Cochabamba

### ISSUE THREAD

**Issue by eduatro** [pyladies/chapter-websites#20]
_This template should be used for those requiring a new PyLadies website._

## What is the name of the PyLadies chapter requesting the website?
Cochabamba

## Have you registered your PyLadies chapter in the PyLadies Chapter Directory?

[X] Yes
[ ] No

## What is the custom domain desired for the PyLadies chapter website?
cbba.pyladies.com
## What are the GitHub handles of the PyLadies chapter organizers?

Name | GitHub Handle | Slack Handle | Team Role 
| --| --| --| --| 
Iris Escobar | irisAdriana | Iris Escobar | co-organizer
Dámaris Gosálvez | damarisgch | Dámaris Gosálvez | Member
Yohana Pelaez | YohanaPelaez | Yohana Pelaez | co-organizer
Paola Céspedes | anypao8 | Paola Céspedes | Member
Eduardo Villarroel | eduatro | | Member

## Do you want your website to use one of the following templates or do you prefer it to be blank?

- [X] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
- [ ] [PyLadies Website served via GitHub Pages with my own design](https://github.com/pyladies/chapter-websites/issues/13#issuecomment-665090083)
- [ ] Fork our existing PyLadies repository to use existing design
       Insert repo name: [Add repo name here]
- [ ] I'll use my own template

## Where will you host the website?

- [X] GitHub Pages
- [ ] Heroku
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
- [X] Completed the 5 questions above
- [X] Did you notify the PyLadies Slack channel #project-tech-infra?
- [x] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2).
      Insert pull request: https://github.com/pyladies/chapter-websites/pull/27
- [ ] If applicable, have you removed your old PyLadies website from main PyLadies repo? 
      Insert pull request: [Add pull request link here]

**For the @pyladies/tech-and-infra-admins to complete:**
- [X] Insert link to repo: https://github.com/pyladies/pyladies-cochabamba-website/tree/gh-pages
- [X] Is the custom domain created? cbba.pyladies.com
- [X] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team: @pyladies/cochabamba 
- [X] Is the GitHub team added to the repo with maintain permissions?

/cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
Uh oh! Looks like that isn't Paola's GitHub handle @eduatro if you want to confirm again: 
<img width="764" alt="image" src="https://user-images.githubusercontent.com/4573607/92803422-0810c600-f37d-11ea-9544-5e1908e6ed03.png">

**Comment by eduatro** [comment]
Sorry @lorenanicole , I was wrong, her username on github is: AnyPaoCS

**Comment by lorenanicole** [comment]
@eduatro done, if you want to let everyone know they have an invite they need  to accept that'd be great! If they don't accept within a few days the invite expires.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/4573607/92948718-6db58e80-f41f-11ea-974d-c2b2e0a43418.png">

**Comment by lorenanicole** [comment]
Additionally @eduatro if you can take care of the rest of any items that are applicable to you all, that's all we need to  close out the issue!
<img width="813" alt="image" src="https://user-images.githubusercontent.com/4573607/92948789-8d4cb700-f41f-11ea-9dc3-0838f323ec34.png">

**Comment by lorenanicole** [comment]
@eduatro  can you please open a pull request to add your website as a submodule to the repository? Example PR: #24. Directions for how to: https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule.

**Comment by eduatro** [comment]
Sure, today I will create that PR. Thanks.

**Comment by eduatro** [comment]
@lorenanicole I created the PR adding the submodule.
I realized that the current subdomain is wrong, should be cbba.pyladies.com instead of https://cochabamba.pyladies.com/ 
I should report that in Slack channel #project-tech-infra?

**Comment by lorenanicole** [comment]
I can change! Apologies that was my oversite.

**Comment by lorenanicole** [comment]
@eduatro we're good https://cbba.pyladies.com is live!
