### ISSUE TITLE
Requesting a new PyLadies Chapter website: Oakland

### ISSUE THREAD

**Issue by BethanyG** [pyladies/chapter-websites#21]
## What is the name of the PyLadies chapter requesting the website? 
Oakland

## Have you registered your PyLadies chapter in the PyLadies Chapter Directory?

[x] Yes
[ ] No

## What is the custom domain desired for the PyLadies chapter website? 
oakland.pyladies.com

## What are the GitHub handles of the PyLadies chapter organizers?

|      Name      	| GitHub Handle 	| Slack Handle 	|   Team Role  	|
|:--------------:	|:-------------:	|:------------:	|:------------:	|
| Linda Peng     	| lpatmo        	| lpnotes      	| co-organizer 	|
| Bethany Garcia 	| bethanyg      	| bethanyg     	| co-organizer 	|

## Do you want your website to use one of the following templates or do you prefer it to be blank?

- [x] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
- [ ] [PyLadies Website served via GitHub Pages with my own design](https://github.com/pyladies/chapter-websites/issues/13#issuecomment-665090083)
- [ ] Fork our existing PyLadies repository to use existing design
       Insert repo name: [Add repo name here]
- [ ] I'll use my own template

## Where will you host the website?

- [x] GitHub Pages
- [ ] Heroku
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
- [x] Completed the 5 questions above
- [x] Did you notify the PyLadies Slack channel #project-tech-infra?
- [ ] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2).
      Insert pull request: [Add pull request link here]
- [ ] If applicable, have you removed your old PyLadies website from main PyLadies repo? 
      Insert pull request: [Add pull request link here]

**For the @pyladies/tech-and-infra-admins to complete:**
- [x] Insert link to repo: https://github.com/pyladies/pyladies-oakland-website
- [X] Is the custom domain created? oakland.pyladies.com
- [x] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team: pyladies/oakland
- [x] Is the GitHub team added to the repo with maintain permissions?

/cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
You're all set. @BethanyG !

**Comment by BethanyG** [comment]
@lorenanicole - Apologies.  I should have made a note on this.  I assigned it to myself because I wasn't done yet with the site. I purposely kept the CNAME empty until I could come back to it.  I was intending to come back to it but go swamped with other work.  Any way we can back this out until I have Oakalands site done?  Right now, the template is live.

**Comment by lorenanicole** [comment]
I set the domain up for you! Check it out at https://oakland.pyladies.com/. Since this ticket is only meant for creating the website we should be done. Unless is there something I'm missing?
