### ISSUE TITLE
Requesting a new PyLadies Chapter website: Guatemala City

### ISSUE THREAD

**Issue by montjoile** [pyladies/chapter-websites#25]
_This template should be used for those requiring a new PyLadies website._

## Have you registered your PyLadies chapter in the PyLadies Chapter Directory?

[x] Yes
[ ] No

## What is the custom domain desired for the PyLadies chapter website?
guatemalacity.pyladies.com

## What are the GitHub handles of the PyLadies chapter organizers?

Name | GitHub Handle | Slack Handle | Team Role 
| Sara Iris Garcia | montjoile | sara Iris Garcia | Chapter lead | 
| Maria Mercedes Wyss | itrjwyss | itrjwyss | Chapter lead | 

## Do you want your website to use one of the following templates or do you prefer it to be blank?

- [ ] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
- [ ] [PyLadies Website served via GitHub Pages with my own design](https://github.com/pyladies/chapter-websites/issues/13#issuecomment-665090083)
- [ ] Fork our existing PyLadies repository to use existing design
       Insert repo name: [Add repo name here]
- [x] I'll use my own template

## Where will you host the website?

- [x] GitHub Pages
- [ ] Heroku
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
- [x] Completed the 5 questions above
- [x] Did you notify the PyLadies Slack channel #project-tech-infra?
- [ ] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2).
      Insert pull request: [Add pull request link here]
- [ ] If applicable, have you removed your old PyLadies website from main PyLadies repo? 
      Insert pull request: [Add pull request link here]

**For the @pyladies/tech-and-infra-admins to complete:**
- [X] Insert link to repo: https://github.com/pyladies/pyladies-guatemala-city-website
- [x] Is the custom domain created?
- [X] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team: @pyladies/guatemala-city 
- [X] Is the GitHub team added to the repo with maintain permissions?

/cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
@montjoile you are ready to go! Repo: https://github.com/pyladies/pyladies-guatemala-city-website/

**Comment by lorenanicole** [comment]
@montjoile can you please open a pull request to add your website as a submodule to the repository? Example PR: #24. Directions for how to: https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule.
