### ISSUE TITLE
Requesting a new PyLadies Chapter website: Chennai

### ISSUE THREAD

**Issue by niharikakrishnan** [pyladies/chapter-websites#26]
_This template should be used for those requiring a new PyLadies website._

## Have you registered your PyLadies chapter in the PyLadies Chapter Directory?

[x] Yes
[ ] No

## What is the custom domain desired for the PyLadies chapter website?
chennai.pyladies.com

## What are the GitHub handles of the PyLadies chapter organizers?

Niharika Krishnan | niharikakrishnan | niharikakrishnan | Organizer
Unnati Mishra | CodesbyUnnati | Unnati Mishra | Member

## Do you want your website to use one of the following templates or do you prefer it to be blank?

- [ ] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
- [ ] [PyLadies Website served via GitHub Pages with my own design](https://github.com/pyladies/chapter-websites/issues/13#issuecomment-665090083)
- [ ] Fork our existing PyLadies repository to use existing design
       Insert repo name: [Add repo name here]
- [x] I'll use my own template

## Where will you host the website?

- [x] GitHub Pages
- [ ] Heroku
- [ ] Netlify
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
- [x] Completed the 5 questions above
- [x] Did you notify the PyLadies Slack channel #project-tech-infra?
- [ ] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2).
      Insert pull request: [Add pull request link here]
- [ ] If applicable, have you removed your old PyLadies website from main PyLadies repo? 
      Insert pull request: [Add pull request link here]

**For the @pyladies/tech-and-infra-admins to complete:**
- [X] Insert link to repo: https://github.com/pyladies/pyladies-chennai-website
- [X] Is the custom domain created? Yes
- [X] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team: @pyladies/chennai 
- [X] Is the GitHub team added to the repo with maintain permissions?

/cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
Yikes I'm afraid that there isn't a good way to host on Netlify actually. The PyLadies domain is a Cloudflare domain, and Netlify + Cloudflare [don't play along well](https://www.netlify.com/blog/2017/03/28/why-you-dont-need-cloudflare-with-netlify/). Since your subdomain is going to be in Cloudflare I recommend you use Netlify only for your CI/CD for checking your builds then host on say GitHub pages instead.

**Comment by CodesbyUnnati** [comment]
Okay, then we'll host it on Netlify. Now, do I have to reopen this issue again?

**Comment by lorenanicole** [comment]
> Okay, then we'll host it on Netlify. Now, do I have to reopen this issue again?

You dont want a domain then? Because if you host on Netlify you cannot use a subdomain.

**Comment by CodesbyUnnati** [comment]
Yess, we want one. We have now decided to host it on Github Pages.

**Comment by lorenanicole** [comment]
Ah ok! You're all setup. Sorry for the netlify hosting, maybe in the future there'll be a better way.

**Comment by lorenanicole** [comment]
Please make sure to complete your items so that you can close out this issue:

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/4573607/92781717-fe319780-f369-11ea-9696-cfe5f26de61a.png">

**Comment by lorenanicole** [comment]
Also chennai.pyladies.com is live with the example theme. Feel free to go customize your website to whatever you. want!

**Comment by CodesbyUnnati** [comment]
Thank You!

**Comment by niharikakrishnan** [comment]
> Please make sure to complete your items so that you can close out this issue:
> 
> <img alt="image" width="1053" src="https://user-images.githubusercontent.com/4573607/92781717-fe319780-f369-11ea-9696-cfe5f26de61a.png">

Hi Lorena, our website code is not present in the main PyLadies repo. We've just recently developed our website. Are Point 3 and Point 4 of Issue checklist applicable to us?

**Comment by BethanyG** [comment]
@niharikakrishnan - Since your website is new, point 4 is not applicable.  However, since you are using `chennai.pyladies.com`, you'll want to complete point 3 -- adding your GH pages repo as a submodule to this repo.

**Comment by lorenanicole** [comment]
@niharikakrishnan can you please open a pull request to add your website as a submodule to the repository? Example PR: https://github.com/pyladies/chapter-websites/pull/24. Directions for how to: https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule.

**Comment by niharikakrishnan** [comment]
Hi @lorenanicole , I've added the Chennai website as a submodule and opened a pull request.
