### ISSUE TITLE
Requesting a new PyLadies Chapter website: PyLadies Hermosillo

### ISSUE THREAD

**Issue by FernandaDguez** [pyladies/chapter-websites#29]
_This template should be used for those requiring a new PyLadies website._

## What is the name of the PyLadies chapter requesting the website?
PyLadies Hermosillo
## Have you registered your PyLadies chapter in the PyLadies Chapter Directory?

[x] Yes
[ ] No

## What is the custom domain desired for the PyLadies chapter website?
hermosillo.pyladies.com
## What are the GitHub handles of the PyLadies chapter organizers?

Name | GitHub Handle | Slack Handle | Team Role 
| --| --| --| --| 
|Fernanda Dominguez|FernandaDguez|Fer|Co-Organizer
|Nicole Castillo|nicolecastillo|nicole castillo|Co-Organizer
|Ximena Sandoval|ximenasandoval|Ximena Sandoval|Co-Organizer

## Do you want your website to use one of the following templates or do you prefer it to be blank?

- [x] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
- [ ] [PyLadies Website served via GitHub Pages with my own design](https://github.com/pyladies/chapter-websites/issues/13#issuecomment-665090083)
- [ ] Fork our existing PyLadies repository to use existing design
       Insert repo name: [Add repo name here]
- [ ] I'll use my own template

## Where will you host the website?

- [x] GitHub Pages
- [ ] Heroku
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
- [x] Completed the 5 questions above
- [x] Did you notify the PyLadies Slack channel #project-tech-infra?
- [x] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2).
      Insert pull request: https://github.com/pyladies/chapter-websites/pull/30
- [ ] If applicable, have you removed your old PyLadies website from main PyLadies repo? 
      Insert pull request: [Add pull request link here]

**For the @pyladies/tech-and-infra-admins to complete:**
- [X] Insert link to repo: https://github.com/pyladies/pyladies-hermosillo-website
- [X] Is the custom domain created? hermosillo.pyladies.com
- [X] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team: @pyladies/hermosillo 
- [x] Is the GitHub team added to the repo with maintain permissions?

/cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
@FernandaDguez tu repo esta aqui 👉  https://github.com/pyladies/pyladies-hermosillo-website/! 

Now if you can you complete the following checklist we'll be good to go 👇 

<img width="945" alt="image" src="https://user-images.githubusercontent.com/4573607/95394801-d1b66000-08c2-11eb-96de-e348d104720a.png">

**Comment by FernandaDguez** [comment]
Thanks a lot, there you go!

**Comment by lorenanicole** [comment]
You're all set!
