### ISSUE TITLE
Requesting a new PyLadies Chapter website: Uruguay

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/chapter-websites#3]
_This template should be used for those requiring a new PyLadies website._

## What is the name of the PyLadies chapter requesting the website?

PyLadies Uruguay

## What is the custom domain desired for the PyLadies chapter website?

uy.pyladies.com

## What are the GitHub handles of the PyLadies chapter organizers?

Name | GitHub Handle | Slack Handle | Team Role 
| --| --| --| --| 
| Flávia Cardoso | @fcardoso0917 | `@flavia` | Organizer |
| Carolina Gherzo  | @cgherzo | `@Carolina Gherzo` | Organizer

## Do you want your website to use one of the following templates or do you prefer it to be blank?

- [X] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
- [ ] I'll use my own template

## Where will you host the website?

- [X] GitHub Pages
- [ ] Heroku
- [ ] Netlify
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
- [X] Completed the 5 questions above
- [X] Did you notify the PyLadies Slack channel #project-tech-infra?
- [x] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2). Insert pull request: #4 
- [x] If applicable, have you removed your old PyLadies website from [main PyLadies repo](github.com/pyladies/pyladies)? Insert pull request: https://github.com/pyladies/pyladies/pull/510

**For the @pyladies/tech-and-infra-admins to complete:**
- [X] Insert link to repo: https://github.com/pyladies/pyladies-uy-website/
- [X] Is the custom domain created? Yes it is visible at uy.pyladies.com
- [X] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team: https://github.com/orgs/pyladies/teams/uruguay/members @pyladies/uruguay 
- [X] Is the GitHub team added to the repo with maintain permissions? Yes see photo.

![image](https://user-images.githubusercontent.com/4573607/86379828-f14d4500-bc50-11ea-9f7e-351021a546ca.png)

/cc @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
Everything is closed on both sides, closing issue!

**Comment by lorenanicole** [comment]
@fcardoso0917 he reabierto para anadir otras organizadoras al equipo @pyladies/uruguay.

**Comment by fmcard** [comment]
add @cgherzo please

**Comment by lorenanicole** [comment]
Y tambien el nombre de usario en Slack para @cgherzo? Gracias 🙇‍♀️ !

**Comment by fmcard** [comment]
No. en Slack es @Carolina Gherzo
