### ISSUE TITLE
Requesting a new PyLadies Chapter website: <NYC PyLadies>

### ISSUE THREAD

**Issue by reshamas** [pyladies/chapter-websites#8]
_This template should be used for those requiring a new PyLadies website._

## What is the name of the PyLadies chapter requesting the website?
NYC PyLadies

## What is the custom domain desired for the PyLadies chapter website?
nyc.pyladies.com

## What are the GitHub handles of the PyLadies chapter organizers?
reshamas
mferrari3
antoniablair
codeLovingYogi
prith13

Name | GitHub Handle | Slack Handle | Team Role 
| --| --| --| --| 
| Reshama Shaikh | reshamas     | reshama | Co-Organizer |
| Melissa Ferrari    | mferrari3      | melissa | Co-Organizer |
| Antonia Blair       | antoniablair  | tonia     | Co-Organizer |
| Felice Ho            | codeLovingYogi | felice | Co-Organizer |
| Prithvi Gandhi    | prith13                | prithvi | Co-Organizer | 

## Do you want your website to use one of the following templates or do you prefer it to be blank?

- [x] [PyLadies Netlify HTML Basic Website](https://github.com/pyladies/netlify-website-template), example: chicago.pyladies.com
- [] I'll use my own template

## Where will you host the website?

- [x] GitHub Pages
- [ ] Heroku
- [ ] Netlify
- [ ] Other: [Please specify as this is needed for @pyladies/tech-and-infra-admins to setup the DNS record accordingly]

## Issue checklist

**For the author to complete:**
- [x] Completed the 5 questions above
- [x] Did you notify the PyLadies Slack channel #project-tech-infra?
- [x] Have you added [your PyLadies chapter website as a submodule](https://github.com/pyladies/chapter-websites#adding-your-website-to-a-submodule) to this repository? Here's an [example pull request adding Chicago to the repo](https://github.com/pyladies/chapter-websites/pull/2).
      Insert pull request: https://github.com/pyladies/chapter-websites/pull/7
- [x] If applicable, have you removed your old PyLadies website from main PyLadies repo? 
      Insert pull request: https://github.com/pyladies/pyladies/pull/520

**For the @pyladies/tech-and-infra-admins to complete:**
- [X] Insert link to repo: https://github.com/pyladies/pyladies-nyc-website/
- [X] Is the custom domain created?
- [X] Are the organizers added to a PyLadies team with proper permissions for the repo? Insert name of the team: @pyladies/nyc 
- [X] Is the GitHub team added to the repo with maintain permissions?

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/4573607/86520314-7595f880-be08-11ea-95bc-ebefb7369923.png">

/cc @pyladies/tech-and-infra-admins

## Note
I would prefer to wait until this PR is accepted before deleting the info from the main pyladies repo, unless there is some other workflow?

**Comment by lorenanicole** [comment]
@reshamas updated! Re:

> # Note
> I would prefer to wait until this PR is accepted before deleting the info from the main pyladies repo, unless there is some other workflow?

What we are looking for is the pull request has been opened and linked in the issue. That removes the need for the @pyladies/tech-and-infra-admins to have to do that step. If you can open that PR and link I'd appreciate it!

**Comment by reshamas** [comment]
@lorenanicole 
Should I submit a PR and delete this:
https://github.com/pyladies/pyladies/tree/main/nyc

**Comment by reshamas** [comment]
@lorenanicole 
In the members, I see that there are only 2 members in the team:  "NYC".
Are we able to add in the other NYC organizers?

**Comment by lorenanicole** [comment]
> @lorenanicole 
> 
> In the members, I see that there are only 2 members in the team:  "NYC".
> 
> Are we able to add in the other NYC organizers?
> 
> 

They have all been invited. They just need to accept.

**Comment by lorenanicole** [comment]
> @lorenanicole 
> 
> Should I submit a PR and delete this:
> 
> https://github.com/pyladies/pyladies/tree/main/nyc
> 
> 

Yup!

**Comment by lorenanicole** [comment]
Thanks @reshamas! We are all done 🎊 !!!

**Comment by lorenanicole** [comment]
@reshamas it appears none of the other NYC organizers have accepted their invite to join the @pyladies/nyc team. Can you please follow up with them to ensure they do? I just resent all their invites today.

![image](https://user-images.githubusercontent.com/4573607/88680085-bc000f80-d0b5-11ea-8d7d-ee54fcaa0182.png)

**Comment by reshamas** [comment]
> @reshamas it appears none of the other NYC organizers have accepted their invite to join the @pyladies/nyc team. Can you please follow up with them to ensure they do? I just resent all their invites today.
> 
> ![image](https://user-images.githubusercontent.com/4573607/88680085-bc000f80-d0b5-11ea-8d7d-ee54fcaa0182.png)

@lorenanicole 
I followed up.  Are there still outstanding invites?

**Comment by BethanyG** [comment]
@reshamas  -- Just checked this evening (8/2/2020), and no-one else for NYC has accepted their invites yet.
